### ISSUE TITLE
Refactor server management logic

### ISSUE THREAD

**Issue by sbruchmann** [sbruchmann/brackets-static-preview#3]
In order to keep things maintainable, server management logic should be refactored. This will keep things DRY when more UI is added.
## Tasks
- [x] Create `server/ServerManager.js` (83c94a7)
- [x] Refactor `node/domain.js`  
  - [x] Move `node/domain.js` to `server/ServerDomain.js` (4d78feb)
  - [x] Split domain and server into two modules (c10c566)
- [x] Refactor `shared-properties.json`
  - [x] Rename to `server/DomainConfig.json` (09abd62)
  - [x] Refactor (42b6fef)
- [x] Improve state management (5de8242)
  - [x] Implement state change event (7fd965d)
- [x] Clean up `main.js`
  - [x] Move configuration of `ServerManager.launchServer` to itself (f61cca8)
  - [x] Toggle menu item on `ServerManager`'s `stateChange` event (a573a86)
